const AUTH = {
  TOKEN: 'AUTH_TOKEN',
  ERRMESSAGE: 'ERR_MESSAGE'
};

const COMPONENT = {
  ERRMESSAGE: 'ERR_MESSAGE',
  ON_ACCOUNTS_SUCCESS: 'ON_ACCOUNTS_SUCCESS',
  ON_CATEGORIES_SUCCESS: 'ON_CATEGORIES_SUCCESS',
  ON_MERCHANTS_SUCCESS: 'ON_MERCHANTS_SUCCESS',
  ON_PLANNING_SUCCESS: 'ON_PLANNING_SUCCESS',
  ON_SPENDING_SUCCESS: 'ON_SPENDING_SUCCESS',
  ON_LINECHART_SUCCESS: 'ON_LINECHART_SUCCESS',
  ON_SETTINGS_SUCCESS: 'ON_SETTINGS_SUCCESS',
  ON_REQUEST_LOAD :'ON_REQUEST_LOAD'
};

const FILTER = {
  ON_CATEGORY_FILTER_SUCCESS: 'ON_CATEGORY_FILTER_SUCCESS',
  ON_SEARCH_TEXT_SUCCESS: 'ON_SEARCH_TEXT_SUCCESS'
}

const TYPES = {
  AUTH,
  COMPONENT,
  FILTER
};

export default TYPES;
